library(Rgadget)
library(unittest, quietly = TRUE)
library(magrittr)
source('utils/helpers.R')

ver_string <- paste("; Generated by Rgadget", packageVersion("Rgadget"))

# Write string into temporary directory and read it back again as a gadget file
read.gadget.string <- function(..., file_type = "generic") {
    dir <- tempfile()
    dir.create(dir)
    writeLines(c(...), con = file.path(dir, "wibble"))
    read.gadget.file(dir, "wibble", file_type = file_type)
}

ok_group("Can create new stocks with some default content", {
    path <- tempfile()

    gadgetstock('codimm', path, missingOkay = TRUE) %>%  # Create a skeleton if missing
        gadget_update('stock', minage = 2, maxage = 4) %>%
        gadget_update('doeseat', maxconsumption = 100, halffeedingvalue = 70) %>%
        gadget_update('doesrenew', minlength = 2, maxlength = 4, dl = 1) %>%
        write.gadget.file(path)
    ok(cmp(dir_list(path), list(
        codimm = c(
            ver_string,
            "stockname\tcodimm",
            "livesonareas\t",
            "minage\t2",
            "maxage\t4",
            "minlength\t",
            "maxlength\t",
            "dl\t",
            "refweightfile\t",
            "growthandeatlengths\t",
            "doesgrow\t0",
            "naturalmortality\t0.2\t0.2\t0.2",
            "iseaten\t0",
            "doeseat\t1", "maxconsumption\t100", "halffeedingvalue\t70",
            "initialconditions",
            "doesmigrate\t0", "doesmature\t0", "doesmove\t0",
            "doesrenew\t1", "minlength\t2", "maxlength\t4", "dl\t1",
            "doesspawn\t0", "doesstray\t0",
        NULL),
        main = c(
            ver_string,
            "timefile\t",
            "areafile\t",
            "printfiles\t; Required comment",
            "[stock]",
            "stockfiles\tcodimm",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL)
    )), "Wrote out stock file")

    gadgetstock('codimm', path, missingOkay = FALSE) %>%
        gadget_update('stock', maxage = 6, minlength = 10, maxlength = 20) %>%
        gadget_update('renewal', 0) %>% # Doesn't renew anymore, we use component name alias
        write.gadget.file(path)
    ok(cmp(dir_list(path), list(
        codimm = c(
            ver_string,
            "stockname\tcodimm",
            "livesonareas\t",
            "minage\t2",
            "maxage\t6",
            "minlength\t10",
            "maxlength\t20",
            "dl\t",
            "refweightfile\t",
            "growthandeatlengths\t",
            "doesgrow\t0",
            "naturalmortality\t0.2\t0.2\t0.2\t0.2\t0.2", # NB: Now with extra defaults
            "iseaten\t0",
            "doeseat\t1", "maxconsumption\t100", "halffeedingvalue\t70",
            "initialconditions",
            "doesmigrate\t0", "doesmature\t0", "doesmove\t0",
            "doesrenew\t0", "doesspawn\t0", "doesstray\t0",
        NULL),
        main = c(
            ver_string,
            "timefile\t",
            "areafile\t",
            "printfiles\t; Required comment",
            "[stock]",
            "stockfiles\tcodimm",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL)
    )), "Updated existing stock file")

    gadgetstock('codmat', path, missingOkay = TRUE) %>%
        write.gadget.file(path)
    ok(cmp(dir_list(path), list(
        codimm = c(
            ver_string,
            "stockname\tcodimm",
            "livesonareas\t",
            "minage\t2",
            "maxage\t6",
            "minlength\t10",
            "maxlength\t20",
            "dl\t",
            "refweightfile\t",
            "growthandeatlengths\t",
            "doesgrow\t0",
            "naturalmortality\t0.2\t0.2\t0.2\t0.2\t0.2",
            "iseaten\t0",
            "doeseat\t1", "maxconsumption\t100", "halffeedingvalue\t70",
            "initialconditions",
            "doesmigrate\t0", "doesmature\t0", "doesmove\t0",
            "doesrenew\t0", "doesspawn\t0", "doesstray\t0",
        NULL),
        codmat = c(
            ver_string,
            "stockname\tcodmat",
            "livesonareas\t",
            "minage\t",
            "maxage\t",
            "minlength\t",
            "maxlength\t",
            "dl\t",
            "refweightfile\t",
            "growthandeatlengths\t",
            "doesgrow\t0",
            "naturalmortality\t",
            "iseaten\t0", "doeseat\t0",
            "initialconditions",
            "doesmigrate\t0", "doesmature\t0", "doesmove\t0",
            "doesrenew\t0", "doesspawn\t0", "doesstray\t0",
        NULL),
        main = c(
            ver_string,
            "timefile\t",
            "areafile\t",
            "printfiles\t; Required comment",
            "[stock]",
            "stockfiles\tcodimm\tcodmat",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL)
    )), "Added new stock file, left old one alone")

    gadgetstock('codmat', path, missingOkay = TRUE) %>%
        gadget_update('doesmigrate', 
            yearstepfile = gadgetfile('data/yearstepfile', components = list(
                data.frame(year = 1998, step = 1:4, matrix = 'codmat-migration'))),
            definematrices = gadgetfile('data/migratematrix', components = list(
                migrationmatrix = list(name = 'codmat-migration'),
                data.frame(1:4, 1:4, 1:4, 1:4)))) %>%
        write.gadget.file(path)
    ok(cmp(dir_list(path), list(
        codimm = c(
            ver_string,
            "stockname\tcodimm",
            "livesonareas\t",
            "minage\t2",
            "maxage\t6",
            "minlength\t10",
            "maxlength\t20",
            "dl\t",
            "refweightfile\t",
            "growthandeatlengths\t",
            "doesgrow\t0",
            "naturalmortality\t0.2\t0.2\t0.2\t0.2\t0.2",
            "iseaten\t0",
            "doeseat\t1", "maxconsumption\t100", "halffeedingvalue\t70",
            "initialconditions",
            "doesmigrate\t0", "doesmature\t0", "doesmove\t0",
            "doesrenew\t0", "doesspawn\t0", "doesstray\t0",
        NULL),
        codmat = c(
            ver_string,
            "stockname\tcodmat",
            "livesonareas\t",
            "minage\t",
            "maxage\t",
            "minlength\t",
            "maxlength\t",
            "dl\t",
            "refweightfile\t",
            "growthandeatlengths\t",
            "doesgrow\t0",
            "naturalmortality\t",
            "iseaten\t0",
            "doeseat\t0",
            "initialconditions",
            "doesmigrate\t1", "yearstepfile\tdata/yearstepfile", "definematrices\tdata/migratematrix",
            "doesmature\t0", "doesmove\t0",
            "doesrenew\t0", "doesspawn\t0", "doesstray\t0",
        NULL),
        "data/migratematrix" = c(
            ver_string,
            "[migrationmatrix]",
            "name\tcodmat-migration",
            "; -- data --",
            "; X1.4\tX1.4.1\tX1.4.2\tX1.4.3",
            "1\t1\t1\t1",
            "2\t2\t2\t2",
            "3\t3\t3\t3",
            "4\t4\t4\t4",
        NULL),
        "data/yearstepfile" = c(
            ver_string,
            "; -- data --",
            "; year\tstep\tmatrix",
            "1998\t1\tcodmat-migration",
            "1998\t2\tcodmat-migration",
            "1998\t3\tcodmat-migration",
            "1998\t4\tcodmat-migration",
        NULL),
        main = c(
            ver_string,
            "timefile\t",
            "areafile\t",
            "printfiles\t; Required comment",
            "[stock]",
            "stockfiles\tcodimm\tcodmat",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL)
    )), "Added new stock file, left old one alone")
})

ok_group("Can detect some GADGET errors", {
    path <- tempfile()

    s <- gadgetstock('codimm', path, missingOkay = TRUE)
    ok(cmp_error(
        gadget_update(s, 'idontexist', minage = 2, maxage = 4),
        "idontexist.*stock.*doesmigrate"), "Noticed bad stock name, suggested proper ones")

})

ok_group("Can populate naturalmortality", {
    path <- tempfile()

    gadgetstock('codimm', path, missingOkay = TRUE) %>%  # Create a skeleton if missing
        gadget_update('stock', minage = 2, maxage = 10) %>%
        gadget_update('naturalmortality', c(0.5, 0.8)) %>%
        write.gadget.file(path)
    ok(cmp(dir_list(path), list(
        codimm = c(
            ver_string,
            "stockname\tcodimm",
            "livesonareas\t",
            "minage\t2",
            "maxage\t10",
            "minlength\t",
            "maxlength\t",
            "dl\t",
            "refweightfile\t",
            "growthandeatlengths\t",
            "doesgrow\t0",
            "naturalmortality\t0.5\t0.8\t0.2\t0.2\t0.2\t0.2\t0.2\t0.2\t0.2",
            "iseaten\t0",
            "doeseat\t0",
            "initialconditions",
            "doesmigrate\t0", "doesmature\t0", "doesmove\t0",
            "doesrenew\t0",
            "doesspawn\t0", "doesstray\t0",
        NULL),
        main = c(
            ver_string,
            "timefile\t",
            "areafile\t",
            "printfiles\t; Required comment",
            "[stock]",
            "stockfiles\tcodimm",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL)
    )), "naturalmortality as long as age-groups, values given at start")

})

ok_group("Doesgrow defaults", {
    path <- tempfile()

    gadgetstock('codimm', path, missingOkay = TRUE) %>%  # Create a skeleton if missing
        gadget_update('stock', minage = 2, maxage = 10) %>%
        gadget_update('doesgrow', 1) %>%
        write.gadget.file(path)
    ok(cmp(dir_list(path)$codimm, c(
        ver_string,
        "stockname\tcodimm",
        "livesonareas\t",
        "minage\t2",
        "maxage\t10",
        "minlength\t",
        "maxlength\t",
        "dl\t",
        "refweightfile\t",
        "growthandeatlengths\t",
        "doesgrow\t1",
        "growthfunction\tlengthvbsimple",
        "growthparameters\t#codimm.Linf\t( * 0.001 #k)\t#walpha\t#wbeta",
        "beta\t(* 10 #bbin)",
        "maxlengthgroupgrowth\t15",
        "naturalmortality\t0.2\t0.2\t0.2\t0.2\t0.2\t0.2\t0.2\t0.2\t0.2",
        "iseaten\t0",
        "doeseat\t0",
        "initialconditions",
        "doesmigrate\t0", "doesmature\t0", "doesmove\t0",
        "doesrenew\t0",
        "doesspawn\t0", "doesstray\t0",
        NULL)
    ), "Default values for doesgrow filled in")

})

ok_group("Refweight from a data.frame", {
    path <- tempfile()

    gadgetstock('codimm', path, missingOkay = TRUE) %>%  # Create a skeleton if missing
        gadget_update('refweight', data = data.frame(length = c(2,4,6,8,10), weight = 11:15)) %>%
        write.gadget.file(path)
    ok(cmp(dir_list(path), list(
        codimm = c(
            ver_string,
            "stockname\tcodimm",
            "livesonareas\t",
            "minage\t",
            "maxage\t",
            "minlength\t2",
            "maxlength\t10",
            "dl\t2",
            "refweightfile\tModelfiles/codimm.refwgt",
            "growthandeatlengths\t",
            "doesgrow\t0",
            "naturalmortality\t",
            "iseaten\t0",
            "doeseat\t0",
            "initialconditions",
            "doesmigrate\t0", "doesmature\t0", "doesmove\t0",
            "doesrenew\t0",
            "doesspawn\t0", "doesstray\t0",
        NULL),
        main = c(
            ver_string,
            "timefile\t",
            "areafile\t",
            "printfiles\t; Required comment",
            "[stock]",
            "stockfiles\tcodimm",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL),
        "Modelfiles/codimm.refwgt" = c(
            ver_string,
            "; -- data --",
            "; length\tweight",
            "2\t11", "4\t12", "6\t13", "8\t14", "10\t15",
        NULL)
    )), "refweight tables both create table and update min/max/dl")
})


# TODO: Tests for mfdb-derived data
