library(Rgadget)
library(unittest, quietly = TRUE)
source('utils/helpers.R')

ver_string <- paste("; Generated by Rgadget", packageVersion("Rgadget"))

# Write string into temporary directory and read it back again as a gadget file
read.gadget.string <- function(..., file_type = "generic") {
    dir <- tempfile()
    dir.create(dir)
    writeLines(c(...), con = file.path(dir, "wibble"))
    read.gadget.file(dir, "wibble", file_type = file_type)
}

# Test we can go from string to object and back again
test_loopback <- function(..., file_type = "generic") {
    file_name <- "loopback"
    dir <- tempfile()
    dir.create(dir)
    writeLines(c(...), con = file.path(dir, file_name))

    gf <- read.gadget.file(dir, file_name, file_type = file_type)
    write.gadget.file(gf, dir)
    ok(cmp(dir_list(dir)[[file_name]], c(...)), paste0(c(...)[[2]], c(...)[[3]]))
}

unattr <- function(x) {
    if(length(names(x)) == 0) {
        attributes(x) <- NULL
    } else if(sum(nchar(names(x))) == 0) {
        # All zero-length names is the same as no names
        attributes(x) <- NULL
    } else {
        attributes(x) <- list(names = names(x))
    }
    return(x)
}

ok_group("Can generate gadgetfile objects", {
    ok(cmp_error(gadgetfile(), "file_name"), "Can't make a gadgetfile without filename")

    ok("gadgetfile" %in% class(gadgetfile("wibble")))
})

ok_group("Can write arbitary data files", {
    dir <- tempfile()

    write.gadget.file(gadgetfile("wobble", components = list(list(
        cabbage = "yes",
        potatoes = c("1 potato", "2 potato", "3 potato", "4!"),
        sprouts = 'Like, "Eeeew!"'))), dir)
    ok(cmp(dir_list(dir), list(
        wobble = c(
            ver_string,
            "cabbage\tyes",
            "potatoes\t1 potato\t2 potato\t3 potato\t4!",
            'sprouts\tLike, "Eeeew!"',
        NULL)
    )), "Wrote out simple gadget file")

    write.gadget.file(gadgetfile("sub/wabble",
        components = list(list(cabbage = "no"))), dir)
    ok(cmp(dir_list(dir), list(
        "sub/wabble" = c(
            ver_string,
            "cabbage\tno",
        NULL),
        wobble = c(
            ver_string,
            "cabbage\tyes",
            "potatoes\t1 potato\t2 potato\t3 potato\t4!",
            'sprouts\tLike, "Eeeew!"',
        NULL)
    )), "Wrote out extra file in subdir")

    write.gadget.file(gadgetfile("sub/wabble", components = list(list(
        cabbage = "ick",
        cauliflower = "yum"))), dir)
    ok(cmp(dir_list(dir), list(
        "sub/wabble" = c(
            ver_string,
            "cabbage\tick",
            "cauliflower\tyum",
        NULL),
        wobble = c(
            ver_string,
            "cabbage\tyes",
            "potatoes\t1 potato\t2 potato\t3 potato\t4!",
            'sprouts\tLike, "Eeeew!"',
        NULL)
    )), "Overwrote a gadget file")
})

ok_group("Can add components and preambles", {
    dir <- tempfile()
    gf <- gadgetfile("wibble",
        components = list(
            structure(list(sprouts = 'Like, "Eeeew!"'), preamble = "Carrots"),
            component = structure(list(name = "component1"), preamble = list("The first component", "I like it")),
            component = structure(list(name = "component2"), preamble = "The second component (with the same name)"),
            tea = structure(list(milk = 1, sugars = 2), preamble = "Tea, please")))
    write.gadget.file(gf, dir)

    ok(cmp(dir_list(dir), list(
        wibble = c(
            ver_string,
            "; Carrots",
            'sprouts\tLike, "Eeeew!"',
            '; The first component',
            '; I like it',
            '[component]',
            'name\tcomponent1',
            '; The second component (with the same name)',
            '[component]',
            'name\tcomponent2',
            '; Tea, please',
            '[tea]',
            'milk\t1',
            'sugars\t2',
        NULL)
    )), "Multiple components with preambles")
})

ok_group("Can include tabular data", {
    dir <- tempfile()
    gf <- gadgetfile("wabble",
        components = list(data.frame(a = c(1,3), b = c(2,5))))
    write.gadget.file(gf, dir)

    ok(cmp(dir_list(dir), list(
        wabble = c(
            ver_string,
            "; -- data --",
            "; a\tb",
            "1\t2",
            "3\t5",
        NULL)
    )), "Tabular data")
})

ok_group("Can nest gadgetfile objects", {
    dir <- tempfile()

    main <- gadgetfile("courses/main",
        components = list(list(cabbage = "yes", potatoes = "2")))
    dessert <- gadgetfile("courses/dessert",
        components = list(list(victoria_sponge = "yes")))
    dinner <- gadgetfile("dinner",
        components = list(list(firstcourse = main, secondcourse = dessert)))

    ok(cmp(capture.output(print(dinner)), c(
        ver_string,
        "firstcourse\tcourses/main",
        "secondcourse\tcourses/dessert",
    NULL)), "Wrote filenames for gadgetfile values")

    write.gadget.file(dinner, dir)
    ok(cmp(dir_list(dir), list(
        "courses/dessert" = c(
            ver_string,
            "victoria_sponge\tyes",
        NULL),
        "courses/main" = c(
            ver_string,
            "cabbage\tyes",
            "potatoes\t2",
        NULL),
        dinner = c(
            ver_string,
            "firstcourse\tcourses/main",
            "secondcourse\tcourses/dessert",
        NULL)
    )), "Wrote out nested gadget files")
})

ok_group("Can read gadget files", {
    ok(cmp_error(read.gadget.file(dir, 'exist/ant'), "exist/ant"),
        "Complain about missing file")
    gf <- read.gadget.file(dir, 'non-exist/ant', missingOkay = TRUE)
    ok(cmp(unattr(gf), list()), "Get an empty gadget file if missingOkay")

    # Basic structure
    gf <- read.gadget.string(
        ver_string,
        "a\t2",
        "b\t4",
        file_type = "generic")
    ok(cmp(
        unattr(gf),
        list(list(a = 2, b = 4))), "Components read")

    # Strings / numbers
    gf <- read.gadget.string(
        ver_string,
        "allnumber\t2\t4\t6\t8",
        "allstring\twho\tdo\twe\tappreciate?",
        "mix\t1\tpotato\t2\tpotato\t3\tpotato\t4!",
        file_type = "generic")
    ok(cmp(
        unattr(gf),
        list(list(
            allnumber = c(2,4,6,8),
            allstring = c("who", "do", "we", "appreciate?"),
            mix = c("1", "potato", "2", "potato", "3", "potato", "4!")))), "Strings/numbers read")

    # Comments and components
    gf <- read.gadget.string(
        ver_string,
        "; This is a comment that should be preserved",
        "a\t6",
        "b\t8",
        "; This is a comment associated with the component below",
        "; So is this",
        "[carrots]",
        "; This is a line preamble",
        "like\tYes I do",
        "; Not this",
        "[carrots]",
        "like\tNo thanks",
        file_type = "generic")
    ok(cmp(
        unattr(gf),
        list(
            structure(list(a = 6, b = 8), preamble = list("This is a comment that should be preserved")),
            carrots = structure(
                list(like = structure("Yes I do", preamble = list("This is a line preamble"))),
                preamble = list("This is a comment associated with the component below", "So is this")),
            carrots = structure(
                list(like = "No thanks"),
                preamble = list("Not this")))), "Components / preamble read")

    # Data
    gf <- read.gadget.string(
        ver_string,
        "a\t99",
        "; Preamble for data",
        "; -- data --",
        "; col\tcolm\tcolt\tcoal",
        "3\t5\t9\t3",
        "7\t5\t33\t3",
        "3\t2\t9\t4",
        file_type = "generic")
    ok(cmp(unattr(gf), list(
        list(a = 99),
        structure(
            data.frame(col = as.integer(c(3,7,3)), colm = as.integer(c(5,5,2)), colt = as.integer(c(9,33,9)), coal = as.integer(c(3,3,4))),
            preamble = list("Preamble for data")))), "Data with preable")

    # Blank preamble lines get preserved
    test_loopback(
        ver_string,
        "a\t45",
        "; ",
        "[component]",
        "fish\tbattered")

    # Can have multiple lines with the same key
    test_loopback(
        ver_string,
        "a\t45",
        "a\t46",
        "a\t47")

    # Can have empty initial components
    test_loopback(
        ver_string,
        "[component]",
        "a\t46",
        "[component]",
        "a\t47")

    # Can have comments at the end of lines too
    test_loopback(
        ver_string,
        "; This is a preamble comment",
        "[component]",
        "a\t46\t\t; This is a comment at the end of a line",
        "a\t46\t47\t48\t49\t\t; This is a comment at the end of multiple values",
        "a\t; This is a comment at the end of an empty line")
})

ok_group("Bare component labels", {
    gf <- read.gadget.string(
        ver_string,
        "farmer\tgiles",
        "cows",
        "fresian\tdaisy",
        "highland\tbessie",
        "pigs",
        "oldspot\tgeorge",
        "pigs\thenry\tfreddie",
        file_type = "generic")
    ok(cmp(unattr(gf), list(list(
        farmer = "giles",
        cows = c(1)[c()],
        fresian = "daisy",
        highland = "bessie",
        pigs = c(1)[c()],
        oldspot = "george",
        pigs = c("henry", "freddie")
        ))), "By default, lines are just extra key/value fields")

    gf <- read.gadget.string(
        ver_string,
        "farmer\tgiles",
        "cows",
        "fresian\tdaisy",
        "highland\tbessie",
        "pigs",
        "oldspot\tgeorge",
        "pigs\thenry\tfreddie",
        file_type = "area")  # i.e. one with bare_component on
    ok(cmp(unattr(gf), list(
        list(farmer = "giles"),
        cows = list(fresian = "daisy", highland = "bessie"),
        pigs = list(oldspot = "george", pigs = c("henry", "freddie"))
        )), "Bare_component turns these into items")

    test_loopback(
        ver_string,
        "farmer\tgiles",
        "cows",
        "fresian\tdaisy",
        "highland\tbessie",
        "pigs",
        "oldspot\tgeorge",
        "pigs\thenry\tfreddie",
        file_type = "area")  # i.e. one with bare_component on
})

ok_group("Implicit component labels", {
    gf <- read.gadget.string(
        ver_string,
        "farmer\tgiles",
        "cows\t2",
        "fresian\tdaisy",
        "highland\tbessie",
        "pigs\t4",
        "oldspot\tgeorge",
        "gloucester\thenry\tfreddie",
        file_type = "generic")
    ok(cmp(unattr(gf), list(list(
        farmer = "giles",
        cows = 2,
        fresian = "daisy",
        highland = "bessie",
        pigs = 4,
        oldspot = "george",
        gloucester = c("henry", "freddie")
        ))), "By default, lines are just extra key/value fields")

    gf <- read.gadget.string(
        ver_string,
        "farmer\tgiles",
        "doesgrow\t2",
        "fresian\tdaisy",
        "highland\tbessie",
        "doeseat\t4",
        "oldspot\tgeorge",
        "gloucester\thenry\tfreddie",
        file_type = "stock")
    ok(cmp(unattr(gf), list(
        list(farmer = "giles"),
        doesgrow = list(doesgrow = 2, fresian = "daisy", highland = "bessie"),
        doeseat = list(doeseat = 4, oldspot = "george", gloucester = c("henry", "freddie"))
        )), "Turn on implicit components, and they get divided")

    test_loopback(
        ver_string,
        "farmer\tgiles",
        "doesgrow\t2",
        "fresian\tdaisy",
        "highland\tbessie",
        "doeseat\t4",
        "oldspot\tgeorge",
        "gloucester\thenry\tfreddie",
        file_type = "stock")
})

ok_group("Writing to mainfile", {
    dir <- tempfile()

    write.gadget.file(gadgetfile("wobble",
        components = list(list(cabbage = "definitely")),
        file_type = "area"), dir)
    ok(cmp(dir_list(dir), list(
        main = c(
            ver_string,
            "timefile\t",
            "areafile\twobble",
            "printfiles\t; Required comment",
            "[stock]",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL),
        wobble = c(
            ver_string,
            "cabbage\tdefinitely",
        NULL)
    )), "Added area file to mainfile")

    write.gadget.file(gadgetfile("wubble",
        components = list(list(cabbage = "nah")),
        file_type = "area"), dir)
    ok(cmp(dir_list(dir), list(
        main = c(
            ver_string,
            "timefile\t",
            "areafile\twubble",
            "printfiles\t; Required comment",
            "[stock]",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL),
        wobble = c(
            ver_string,
            "cabbage\tdefinitely",
        NULL),
        wubble = c(
            ver_string,
            "cabbage\tnah",
        NULL)
    )), "Extra area file replaces old")

    write.gadget.file(gadgetfile("wobble",
        components = list(list(cabbage = "please")),
        file_type = "area"), dir, mainfile = NULL)
    ok(cmp(dir_list(dir), list(
        main = c(
            ver_string,
            "timefile\t",
            "areafile\twubble",
            "printfiles\t; Required comment",
            "[stock]",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
        NULL),
        wobble = c(
            ver_string,
            "cabbage\tplease",
        NULL),
        wubble = c(
            ver_string,
            "cabbage\tnah",
        NULL)
    )), "Don't update mainfile if we disable it")

    write.gadget.file(gadgetfile("likelihood/bubble",
        components = list(list(cabbage = "twice")),
        file_type = "likelihood"), dir)
    write.gadget.file(gadgetfile("likelihood/bobble",
        components = list(list(cabbage = "thrice")),
        file_type = "likelihood"), dir)
    ok(cmp(dir_list(dir), list(
        "likelihood/bobble" = c(
            ver_string,
            "cabbage\tthrice",
        NULL),
        "likelihood/bubble" = c(
            ver_string,
            "cabbage\ttwice",
        NULL),
        main = c(
            ver_string,
            "timefile\t",
            "areafile\twubble",
            "printfiles\t; Required comment",
            "[stock]",
            "[tagging]",
            "[otherfood]",
            "[fleet]",
            "[likelihood]",
            "likelihoodfiles\tlikelihood/bubble\tlikelihood/bobble",
        NULL),
        wobble = c(
            ver_string,
            "cabbage\tplease",
        NULL),
        wubble = c(
            ver_string,
            "cabbage\tnah",
        NULL)
    )), "Can add multiple likelihood files")
})

ok_group("Can read fleet files successfully", {
    path <- tempfile()

    test_loopback(
        ver_string,
        "[fleetcomponent]",
        "totalfleet\tcomm",
        "livesonareas\t1",
        "multiplicative\t1",
        "suitability",
        "codimm\tfunction exponential    #acomm (* 0.01 #bcomm)  0 1",
        "codmat\tfunction exponential    #acomm (* 0.01 #bcomm)  0 1",
        "amount\tData/cod.fleet.data",
        file_type = "fleet")
})
